Add a warning with a redirect to the old docs
OpenNMS/docs.opennms.com pull request #3
Opened 2020-10-15 07:35 UTC by indigo423

To help our people stranded on the new docs .com page.

2020-10-15 18:38 UTC, RangerRick approved these changes

2020-10-19 13:47 UTC, Bonrob2 requested changes
Minor change. Thanks for doing this Ronny!

2020-10-19 13:47 UTC, Bonrob2 commented on start-page/modules/ROOT/pages/index.adoc
> +           This place here is work in progress and not complete.
```suggestion
           This location is work in progress and not complete.
```

2020-10-19 13:47 UTC, Bonrob2 commented on start-page/modules/ROOT/pages/index.adoc
> +           If you want the official OpenNMS documentation, please go to https://docs.opennms.org.
```suggestion
           For the official OpenNMS documentation, please go to https://docs.opennms.org.
```

2020-10-19 13:47 UTC, Bonrob2 commented on start-page/modules/ROOT/pages/index.adoc
> +           Feel free to get in contact with us in our https://chat.opennms.com/opennms/channels/wtd[Chat] if you have questions.
```suggestion
           Feel free to contact us in our https://chat.opennms.com/opennms/channels/wtd[Chat] if you have questions.
```

2020-10-19 14:22 UTC, merged